export const TOKENS = {
  // Repositories (interfaces)
  UserRepository: Symbol('UserRepository'),
  PlatformRoleRepository: Symbol('RoleRepository'),
  OrganizationRepository: Symbol('OrganizationRepository'),
  SubscriptionPlanRepository: Symbol('SubscriptionPlanRepository'),
  FeatureRepository: Symbol('FeatureRepository'),
  NotificationRepository: Symbol('NotificationRepository'),
  AuditLogRepository: Symbol('AuditLogRepository'),
  OrganizationDocumentRepository: Symbol('OrganizationDocumentRepository'),
  PlanFeatureRepository: Symbol('PlanFeatureRepository'),

  RevokeUserSessionsUseCase: Symbol.for('RevokeUserSessionsUseCase'),

  UserResendInviteUseCase: Symbol('ResendInviteUseCase'),
  RequestPasswordResetUseCase: Symbol('RequestPasswordResetUseCase'),
  ResetPasswordUseCase: Symbol('ResetPasswordUseCase'),
  ChangePasswordUseCase: Symbol('ChangePasswordUseCase'),

  // Services (interfaces)
  HashService: Symbol('HashService'),
  TokenService: Symbol('TokenService'),
  WhatsAppNotifierService: Symbol('WhatsAppNotifierService'),
  EmailNotifierService: Symbol('EmailNotifierService'),
  InAppNotifierService: Symbol('InAppNotifierService'),
  NotifierMap: Symbol('NotifierMap'),
  TokenRevocationRegistry: Symbol('TokenRevocationRegistry'),
  FileStorageService: Symbol('FileStorageService'),
  PermissionResolver: Symbol('PermissionResolver'),

  // Use-cases (concrete classes, registered for discoverability/consistency)
  LoginAdminUseCase: Symbol('LoginAdminUseCase'),
  RefreshTokenUseCase: Symbol('RefreshTokenUseCase'),
  GetCurrentUserUseCase: Symbol('GetCurrentUserUseCase'),
  VerifyInviteTokenUseCase: Symbol('VerifyInviteTokenUseCase'),
  AcceptInviteUseCase: Symbol('AcceptInviteUseCase'),
  ResendInviteUseCase: Symbol('ResendInviteUseCase'),
  CreateUserUseCase: Symbol('CreateUserUseCase'),
  EditUserUseCase: Symbol('EditUserUseCase'),
  RevokeSessionsUseCase: Symbol('RevokeSessionsUseCase'),
  CreateRoleUseCase: Symbol('CreateRoleUseCase'),
  EditRoleUseCase: Symbol('EditRoleUseCase'),
  DeleteRoleUseCase: Symbol('DeleteRoleUseCase'),
  CreateOrganizationUseCase: Symbol('CreateOrganizationUseCase'),
  EditOrganizationUseCase: Symbol('EditOrganizationUseCase'),
  DeleteOrganizationUseCase: Symbol('DeleteOrganizationUseCase'),
  UpgradePlanUseCase: Symbol('UpgradePlanUseCase'),
  BlockCustomerUseCase: Symbol('BlockCustomerUseCase'),
  AssignSalesmanUseCase: Symbol('AssignSalesmanUseCase'),
  CreateFeatureUseCase: Symbol('CreateFeatureUseCase'),
  ScheduleNotificationUseCase: Symbol('ScheduleNotificationUseCase'),
  SendReminderUseCase: Symbol('SendReminderUseCase'),
  GetBusinessReportUseCase: Symbol('GetBusinessReportUseCase'),
  OrganizationDocumentUseCase: Symbol('OrganizationDocumentUseCase'),
  UpdateFeatureUseCase: Symbol('UpdateFeatureUseCase'),
  DeleteFeatureUseCase: Symbol('DeleteFeatureUseCase'),
  CreateOrganizationSubscriptionUseCase: Symbol('CreateOrganizationSubscriptionUseCase'),
  RenewOrganizationSubscriptionUseCase: Symbol('RenewOrganizationSubscriptionUseCase'),
  CancelOrganizationSubscriptionUseCase: Symbol('CancelOrganizationSubscriptionUseCase'),
  AddPlanFeatureUseCase: Symbol('AddPlanFeatureUseCase'),
  RemovePlanFeatureUseCase: Symbol('RemovePlanFeatureUseCase'),
  CreateSubscriptionPlanUseCase: Symbol('CreateSubscriptionPlanUseCase'),
  UpdateSubscriptionPlanUseCase: Symbol('UpdateSubscriptionPlanUseCase'),
  DeleteSubscriptionPlanUseCase: Symbol('DeleteSubscriptionPlanUseCase'),
  LogoutAllDevicesUseCase: Symbol('LogoutAllDevicesUseCase'),
  SetOrganizationAdminPasswordUseCase: Symbol('SetOrganizationAdminPasswordUseCase'),
  CancelInviteUseCase: Symbol('CancelInviteUseCase'),

  // Controllers
  AuthController: Symbol('AuthController'),
  RoleController: Symbol('RoleController'),
  OrganizationController: Symbol('OrganizationController'),
  NotificationController: Symbol('NotificationController'),
  DashboardController: Symbol('DashboardController'),
  UserController: Symbol('UserController'),
  AuditLogController: Symbol('AuditLogController'),
  InviteController: Symbol('InviteController'),
  OrganizationDocumentController: Symbol('OrganizationDocumentController'),
  ListRolesUseCase: Symbol('ListRolesUseCase'),
  PlatformUserRepository: Symbol('PlatformUserRepository'),


  // tokens.ts
  CreatePlatformUserUseCase: Symbol('CreatePlatformUserUseCase'),
  EditPlatformUserUseCase: Symbol('EditPlatformUserUseCase'),
  ListPlatformUsersUseCase: Symbol('ListPlatformUsersUseCase'),
  DeletePlatformUserUseCase: Symbol('DeletePlatformUserUseCase'),
  PlatformUserController: Symbol('PlatformUserController'),
  GetPlatformUserUseCase: Symbol('GetPlatformUserUseCase'),
  BlockPlatformUserUseCase: Symbol.for('BlockPlatformUserUseCase'),
  UnblockPlatformUserUseCase: Symbol.for('UnblockPlatformUserUseCase'),
} as const;