export const TOKENS = {
  // Repositories (interfaces)
  UserRepository: Symbol('UserRepository'),
  RoleRepository: Symbol('RoleRepository'),
  PermissionRepository: Symbol('PermissionRepository'),
  OrganizationRepository: Symbol('OrganizationRepository'),
  SubscriptionPlanRepository: Symbol('SubscriptionPlanRepository'),
  FeatureRepository: Symbol('FeatureRepository'),
  NotificationRepository: Symbol('NotificationRepository'),
  AuditLogRepository: Symbol('AuditLogRepository'),

  // Services (interfaces)
  HashService: Symbol('HashService'),
  TokenService: Symbol('TokenService'),
  WhatsAppNotifierService: Symbol('WhatsAppNotifierService'),
  EmailNotifierService: Symbol('EmailNotifierService'),
  InAppNotifierService: Symbol('InAppNotifierService'),
  NotifierMap: Symbol('NotifierMap'),

  // Use-cases (concrete classes, registered for discoverability/consistency)
  LoginAdminUseCase: Symbol('LoginAdminUseCase'),
  RefreshTokenUseCase: Symbol('RefreshTokenUseCase'),
  GetCurrentUserUseCase: Symbol('GetCurrentUserUseCase'),
  VerifyInviteTokenUseCase: Symbol('VerifyInviteTokenUseCase'),
  AcceptInviteUseCase: Symbol('AcceptInviteUseCase'),
  ResendInviteUseCase: Symbol('ResendInviteUseCase'),
  CreateRoleUseCase: Symbol('CreateRoleUseCase'),
  AssignPermissionsUseCase: Symbol('AssignPermissionsUseCase'),
  EditRoleUseCase: Symbol('EditRoleUseCase'),
  DeleteRoleUseCase: Symbol('DeleteRoleUseCase'),
  CreateOrganizationUseCase: Symbol('CreateOrganizationUseCase'),
  EditOrganizationUseCase: Symbol('EditOrganizationUseCase'),
  DeleteOrganizationUseCase: Symbol('DeleteOrganizationUseCase'),
  UpgradePlanUseCase: Symbol('UpgradePlanUseCase'),
  BlockCustomerUseCase: Symbol('BlockCustomerUseCase'),
  AssignSalesmanUseCase: Symbol('AssignSalesmanUseCase'),
  CreatePlanUseCase: Symbol('CreatePlanUseCase'),
  EditPlanUseCase: Symbol('EditPlanUseCase'),
  CreateFeatureUseCase: Symbol('CreateFeatureUseCase'),
  ScheduleNotificationUseCase: Symbol('ScheduleNotificationUseCase'),
  SendReminderUseCase: Symbol('SendReminderUseCase'),
  GetBusinessReportUseCase: Symbol('GetBusinessReportUseCase'),

  // Controllers
  AuthController: Symbol('AuthController'),
  RoleController: Symbol('RoleController'),
  PermissionController: Symbol('PermissionController'),
  OrganizationController: Symbol('OrganizationController'),
  SubscriptionController: Symbol('SubscriptionController'),
  NotificationController: Symbol('NotificationController'),
  DashboardController: Symbol('DashboardController'),
} as const;